# Generated by Django 4.2.6 on 2024-06-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uptated_at',
            new_name='updated_at',
        ),
    ]
