# Generated by Django 4.2.6 on 2024-07-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='List',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task.list'),
            preserve_default=False,
        ),
    ]
