# Generated by Django 5.0.6 on 2024-07-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='List',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.list'),
        ),
    ]
