# Generated by Django 5.0.6 on 2024-08-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.list'),
        ),
    ]
